2020-06-25 16:14:44,082 INFO: Microblog startup [in /Users/elee/practice_docker/microblog/app/__init__.py:77]
2020-06-25 16:14:47,015 ERROR: Exception on /uploadfile [POST] [in /Users/elee/ubuntu/microblog/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/elee/ubuntu/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/elee/ubuntu/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/elee/ubuntu/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/elee/ubuntu/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/elee/ubuntu/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/elee/ubuntu/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/elee/ubuntu/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/Users/elee/practice_docker/microblog/app/main/routes.py", line 183, in upload_file
    file.save(os.path.join(current_app.config['UPLOAD_FOLDER'], filename))
  File "/Users/elee/ubuntu/microblog/venv/lib/python3.7/site-packages/werkzeug/datastructures.py", line 2725, in save
    dst = open(dst, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: '/Users/elee/practice_docker/microblog/uploads/hello_world.txt'
2020-06-25 16:41:16,895 INFO: Microblog startup [in /Users/elee/practice_docker/microblog/app/__init__.py:77]
2020-06-25 16:41:32,355 ERROR: Exception on /uploadfile [POST] [in /Users/elee/ubuntu/microblog/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/elee/ubuntu/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/elee/ubuntu/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/elee/ubuntu/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/elee/ubuntu/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/elee/ubuntu/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/elee/ubuntu/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/elee/ubuntu/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/Users/elee/practice_docker/microblog/app/main/routes.py", line 183, in upload_file
    file.save(os.path.join(current_app.config['UPLOAD_FOLDER'], filename))
  File "/Users/elee/ubuntu/microblog/venv/lib/python3.7/site-packages/werkzeug/datastructures.py", line 2725, in save
    dst = open(dst, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: '/Users/elee/practice_docker/microblog/uploads/hello_world.txt'
2020-06-25 16:48:02,174 INFO: Microblog startup [in /Users/elee/practice_docker/microblog/app/__init__.py:77]
2020-06-25 16:48:33,748 ERROR: Exception on /uploadfile [POST] [in /Users/elee/ubuntu/microblog/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/elee/ubuntu/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/elee/ubuntu/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/elee/ubuntu/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/elee/ubuntu/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/elee/ubuntu/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/elee/ubuntu/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/elee/ubuntu/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/Users/elee/practice_docker/microblog/app/main/routes.py", line 183, in upload_file
    file.save(os.path.join(current_app.config['UPLOAD_FOLDER'], filename))
  File "/Users/elee/ubuntu/microblog/venv/lib/python3.7/site-packages/werkzeug/datastructures.py", line 2725, in save
    dst = open(dst, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: '/Users/elee/practice_docker/microblog/uploads/hello_world.txt'
2020-06-25 16:56:03,364 INFO: Microblog startup [in /Users/elee/practice_docker/microblog/app/__init__.py:78]
2020-06-25 17:05:04,190 INFO: Microblog startup [in /Users/elee/practice_docker/microblog/app/__init__.py:78]
2020-06-25 17:05:12,579 ERROR: Exception on /uploadfile [POST] [in /Users/elee/ubuntu/microblog/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/elee/ubuntu/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/elee/ubuntu/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/elee/ubuntu/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/elee/ubuntu/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/elee/ubuntu/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/elee/ubuntu/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/elee/ubuntu/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/Users/elee/practice_docker/microblog/app/main/routes.py", line 183, in upload_file
    file.save(os.path.join(current_app.config['UPLOAD_FOLDER'], filename))
  File "/Users/elee/ubuntu/microblog/venv/lib/python3.7/site-packages/werkzeug/datastructures.py", line 2725, in save
    dst = open(dst, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: '/Users/elee/practice_docker/microblog/uploads/hello_world.txt'
2020-06-25 17:05:24,375 ERROR: Exception on /uploadfile [POST] [in /Users/elee/ubuntu/microblog/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/elee/ubuntu/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/elee/ubuntu/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/elee/ubuntu/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/elee/ubuntu/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/elee/ubuntu/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/elee/ubuntu/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/elee/ubuntu/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/Users/elee/practice_docker/microblog/app/main/routes.py", line 183, in upload_file
    file.save(os.path.join(current_app.config['UPLOAD_FOLDER'], filename))
  File "/Users/elee/ubuntu/microblog/venv/lib/python3.7/site-packages/werkzeug/datastructures.py", line 2725, in save
    dst = open(dst, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: '/Users/elee/practice_docker/microblog/uploads/hello_world.txt'
2020-06-25 17:16:41,022 INFO: Microblog startup [in /Users/elee/practice_docker/microblog/app/__init__.py:78]
2020-06-25 17:16:43,465 INFO: Microblog startup [in /Users/elee/practice_docker/microblog/app/__init__.py:78]
